---
stages:
    - pre-flight
    - quality
    - test
    - build
    - documentation
    - deploy

include:
    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/root.before_script.yml'

    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/pre-flight/prepare-cache.yml'

    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/.junit-report.yml'

    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/quality/php/compatibility.with-report.yml'
    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/quality/php/duplication.yml'

#    -   project: 'wpml/wpml-plugin-template'
#        file: '.gitlab-ci/test/cc.yml'
#    -   project: 'wpml/wpml-plugin-template'
#        file: '.gitlab-ci/test/unit/jest.with-report.yml'
    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/test/unit/php.with-report.yml'
#    -   project: 'wpml/wpml-plugin-template'
#        file: '.gitlab-ci/test/integration/php.yml'

    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/build/branch.yml'
    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/build/protected-branches.yml'
    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/build/special-branches.yml'
    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/build/tag.yml'

    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/documentation/release-notes.yml'

    -   project: 'wpml/wpml-plugin-template'
        file: '.gitlab-ci/deploy/s3.yml'
