.s3-upload:
    stage: deploy
    extends: .cache-pull
    when: on_success
    image: registry.otgs.work/infrastructure/docker-images/artifacts_builder:php73
    tags:
        - autoscale
    script:
        - zip -qTmr ${FILE_NAME} ${CI_PROJECT_NAME} && echo "Success" || echo "Failed"
        - aws s3 cp ${FILE_NAME} s3://${S3_BUCKET}/${FILE_NAME}

S3:
    extends: .s3-upload
    variables:
        FILE_NAME: '${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}.zip'
    except:
        refs:
            - tags

#S3 Branches:
#    extends: .s3-upload
#    variables:
#        FILE_NAME: '${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}.zip'
#    only:
#        - branches
#    except:
#        refs:
#            - develop
#            - master
#            - stable
#            - bleeding
#
#S3 Protected Branches:
#    extends: .s3-upload
#    variables:
#        FILE_NAME: '${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}.zip'
#    only:
#        refs:
#            - develop
#            - master
#
#S3 Special Branches:
#    extends: .s3-upload
#    variables:
#        FILE_NAME: '${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}.zip'
#    only:
#        refs:
#            - stable
#            - bleeding
#
S3 Tag:
    extends: .s3-upload
    variables:
        FILE_NAME: '${CI_PROJECT_NAME}.${CI_COMMIT_REF_NAME}.zip'
    only:
        refs:
            - tags
