Duplication <PHP>:
    stage: quality
    extends:
        - .cache-pull
    when: on_success
    image: registry.otgs.work/infrastructure/docker-images/phpunit:7.3
    tags:
        - autoscale
    script:
        - >
            if [[ -f vendor/bin/phpcpd ]] ; then
                vendor/bin/phpcpd --exclude=tests --exclude=vendor -- ./
            else
                echo "Duplication checks skipped."
            fi
    only:
        refs:
            - branches
    except:
        refs:
            - stable
            - bleeding
