name: OTGS PHP TEST
run-name: PHP TEST at ${{ github.ref_name }}

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Set github token for composer
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run unit test suite
        run: ./vendor/bin/phpunit

      - name: Run static test suite
        run: ./vendor/bin/phpstan
